# -*- coding: utf-8 -*-
"""Amazon Top 50 Bestselling Books 2009 - 2019

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVX6qx99BBD_RtgYz67-Sze2chmj4ojm
"""

import numpy as np
import pandas as pd

df = pd.read_csv("/content/bestsellers with categories.csv")
df

df.head()

df.shape

df.columns

df.describe()

df.info()

# Clean column names (strip spaces, lowercase, replace spaces with underscores)
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

# Handle missing values (drop rows with any nulls for simplicity)
df.dropna(inplace=True)

# Remove duplicates
df.drop_duplicates(inplace=True)

# Normalize text fields (example: author/title/category to lowercase and stripped)
text_columns = ['name', 'author', 'genre']
for col in text_columns:
    if col in df.columns:
        df[col] = df[col].str.strip().str.lower()

# Optional – convert 'year' to int and 'price' to float
if 'year' in df.columns:
    df['year'] = pd.to_numeric(df['year'], errors='coerce')
if 'price' in df.columns:
    df['price'] = pd.to_numeric(df['price'], errors='coerce')

# Display cleaned data info
print("\nCleaned Data Info:")
print(df.info())

# Save cleaned data to the current working directory
df.to_csv('cleaned_bestsellers.csv', index=False)
print("\nCleaned data saved as 'cleaned_bestsellers.csv' in the current folder.")

# renaming columns
df.rename(columns={"Name": "Title", "Year": "Publication Year", "User Rating": "Rating"}, inplace=True)

# Converting data types
df["price"] = df["price"].astype(float)

# analyzing author popularity
author_counts = df['author'].value_counts()
print(author_counts)

# avg rating by genre
avg_rating_by_genre = df.groupby("genre")["user_rating"].mean()
print(avg_rating_by_genre)

# Export top selling authors to a CSV file
author_counts.head(10).to_csv("top_authors.csv")

# Export average rating by genre to a CSV file
avg_rating_by_genre.to_csv("avg_rating_by_genre.csv")

author_counts

avg_rating_by_genre



